### ISSUE TITLE
Unable to open exported files from dev.blawx.com on my local version

### ISSUE THREAD

**Issue by foxcoleman** [Lexpedite/blawx#565]
I get a deserialization error. 
![image](https://github.com/Lexpedite/blawx/assets/55117702/eb5bbd2b-9a86-4389-9785-822a7140d679)

**Comment by Gauntlet173** [comment]
Hmm... we made a change in a recent version upgrade where instead of using numerical identifiers for projects in the URL, it now uses a slug that is generated from the project name, and the user's name. If you are using an older version locally, the new version will have slug fields and the old version won't know what to do with them. You might just need to upgrade the local installation?

Can you confirm whether the versions are the same?

**Comment by Gauntlet173** [comment]
heard back that the versions are different. closing
